// Enums pour correspondre au schéma Prisma

export enum StoreAisle {
  FRUITS_ET_LEGUMES = 'FRUITS_ET_LEGUMES',
  BOUCHERIE = 'BOUCHERIE',
  VOLAILLE = 'VOLAILLE',
  CHARCUTERIE = 'CHARCUTERIE',
  POISSONNERIE = 'POISSONNERIE',
  ROTISSERIE = 'ROTISSERIE',
  BOULANGERIE = 'BOULANGERIE',
  PATISSERIE = 'PATISSERIE',
  FROMAGERIE = 'FROMAGERIE',
  TRAITEUR = 'TRAITEUR',
  PRODUITS_LAITIERS = 'PRODUITS_LAITIERS',
  OEUFS = 'OEUFS',
  SURGELES = 'SURGELES',
  EPICERIE_SALEE = 'EPICERIE_SALEE',
  PATES_RIZ_CEREALES = 'PATES_RIZ_CEREALES',
  CONSERVES = 'CONSERVES',
  SAUCES_CONDIMENTS = 'SAUCES_CONDIMENTS',
  HUILES_VINAIGRES = 'HUILES_VINAIGRES',
  EPICES_AIDES_CULINAIRES = 'EPICES_AIDES_CULINAIRES',
  PLATS_CUISINES = 'PLATS_CUISINES',
  SNACKING = 'SNACKING',
  EPICERIE_SUCREE = 'EPICERIE_SUCREE',
  BISCUITS_GATEAUX = 'BISCUITS_GATEAUX',
  CHOCOLATS_CONFISERIES = 'CHOCOLATS_CONFISERIES',
  PETIT_DEJEUNER = 'PETIT_DEJEUNER',
  CAFE_THE = 'CAFE_THE',
  EAUX = 'EAUX',
  SODAS_JUS = 'SODAS_JUS',
  BIERES = 'BIERES',
  VINS_SPIRITUEUX = 'VINS_SPIRITUEUX',
  PRODUITS_BIO = 'PRODUITS_BIO',
  SANS_GLUTEN_DIETETIQUE = 'SANS_GLUTEN_DIETETIQUE',
  BEBE = 'BEBE',
  ANIMALERIE = 'ANIMALERIE',
  ENTRETIEN_MAISON = 'ENTRETIEN_MAISON',
  LESSIVE_SOIN_LINGE = 'LESSIVE_SOIN_LINGE',
  PAPIER_HYGIENE_MENAGERE = 'PAPIER_HYGIENE_MENAGERE',
  HYGIENE_BEAUTE = 'HYGIENE_BEAUTE',
  PARAPHARMACIE = 'PARAPHARMACIE',
  PAPETERIE_FOURNITURES = 'PAPETERIE_FOURNITURES',
  PRESSE_LIVRES = 'PRESSE_LIVRES',
  MAISON_DECO = 'MAISON_DECO',
  ARTS_DE_LA_TABLE = 'ARTS_DE_LA_TABLE',
  TEXTILE = 'TEXTILE',
  ELECTROMENAGER = 'ELECTROMENAGER',
  MULTIMEDIA_HIGH_TECH = 'MULTIMEDIA_HIGH_TECH',
  BRICOLAGE = 'BRICOLAGE',
  AUTO_MOBILITE = 'AUTO_MOBILITE',
  JARDIN_PLANTES = 'JARDIN_PLANTES',
  FLEURS = 'FLEURS',
  JEUX_JOUETS = 'JEUX_JOUETS',
  SAISONNIER = 'SAISONNIER',
}

export type StoreAisleType =
  | 'FRUITS_ET_LEGUMES'
  | 'BOUCHERIE'
  | 'VOLAILLE'
  | 'CHARCUTERIE'
  | 'POISSONNERIE'
  | 'ROTISSERIE'
  | 'BOULANGERIE'
  | 'PATISSERIE'
  | 'FROMAGERIE'
  | 'TRAITEUR'
  | 'PRODUITS_LAITIERS'
  | 'OEUFS'
  | 'SURGELES'
  | 'EPICERIE_SALEE'
  | 'PATES_RIZ_CEREALES'
  | 'CONSERVES'
  | 'SAUCES_CONDIMENTS'
  | 'HUILES_VINAIGRES'
  | 'EPICES_AIDES_CULINAIRES'
  | 'PLATS_CUISINES'
  | 'SNACKING'
  | 'EPICERIE_SUCREE'
  | 'BISCUITS_GATEAUX'
  | 'CHOCOLATS_CONFISERIES'
  | 'PETIT_DEJEUNER'
  | 'CAFE_THE'
  | 'EAUX'
  | 'SODAS_JUS'
  | 'BIERES'
  | 'VINS_SPIRITUEUX'
  | 'PRODUITS_BIO'
  | 'SANS_GLUTEN_DIETETIQUE'
  | 'BEBE'
  | 'ANIMALERIE'
  | 'ENTRETIEN_MAISON'
  | 'LESSIVE_SOIN_LINGE'
  | 'PAPIER_HYGIENE_MENAGERE'
  | 'HYGIENE_BEAUTE'
  | 'PARAPHARMACIE'
  | 'PAPETERIE_FOURNITURES'
  | 'PRESSE_LIVRES'
  | 'MAISON_DECO'
  | 'ARTS_DE_LA_TABLE'
  | 'TEXTILE'
  | 'ELECTROMENAGER'
  | 'MULTIMEDIA_HIGH_TECH'
  | 'BRICOLAGE'
  | 'AUTO_MOBILITE'
  | 'JARDIN_PLANTES'
  | 'FLEURS'
  | 'JEUX_JOUETS'
  | 'SAISONNIER';

export enum Unit {
  PINCEE = 'PINCEE',
  GRAMME = 'GRAMME',
  KILOGRAMME = 'KILOGRAMME',
  MILLIGRAMME = 'MILLIGRAMME',
  LITRE = 'LITRE',
  MILLILITRE = 'MILLILITRE',
  CENTILITRE = 'CENTILITRE',
  CUILLERE_A_CAFE = 'CUILLERE_A_CAFE',
  CUILLERE_A_SOUPE = 'CUILLERE_A_SOUPE',
  TASSE = 'TASSE',
  VERRE = 'VERRE',
  BOL = 'BOL',
  UNITE = 'UNITE',
  TRANCHE = 'TRANCHE',
  MORCEAU = 'MORCEAU',
  BRANCHE = 'BRANCHE',
  FEUILLE = 'FEUILLE',
  BOUQUET = 'BOUQUET',
  BOTTE = 'BOTTE',
  GOUSSE = 'GOUSSE',
  ZESTE = 'ZESTE',
  SACHET = 'SACHET',
  BOITE = 'BOITE',
  PAQUET = 'PAQUET',
  POT = 'POT',
  BARQUETTE = 'BARQUETTE',
  ROULEAU = 'ROULEAU',
  BARIL = 'BARIL',
  BOUTEILLE = 'BOUTEILLE',
  TUBE = 'TUBE',
  BIDON = 'BIDON',
  FLACON = 'FLACON',
}

export type UnitType =
  | 'PINCEE'
  | 'GRAMME'
  | 'KILOGRAMME'
  | 'MILLIGRAMME'
  | 'LITRE'
  | 'MILLILITRE'
  | 'CENTILITRE'
  | 'CUILLERE_A_CAFE'
  | 'CUILLERE_A_SOUPE'
  | 'TASSE'
  | 'VERRE'
  | 'BOL'
  | 'UNITE'
  | 'TRANCHE'
  | 'MORCEAU'
  | 'BRANCHE'
  | 'FEUILLE'
  | 'BOUQUET'
  | 'BOTTE'
  | 'GOUSSE'
  | 'ROULEAU'
  | 'BARIL'
  | 'BOUTEILLE'
  | 'TUBE'
  | 'BIDON'
  | 'FLACON'
  | 'ZESTE'
  | 'SACHET'
  | 'BOITE'
  | 'PAQUET'
  | 'POT'
  | 'BARQUETTE';
