// Mapping complet des rayons de magasin vers leurs labels français
// Correspond exactement aux valeurs @map() définies dans prisma/schema.prisma

export const AISLE_LABELS: Record<string, string> = {
  FRUITS_ET_LEGUMES: 'Fruits et légumes',
  BOUCHERIE: 'Boucherie',
  VOLAILLE: 'Volaille',
  CHARCUTERIE: 'Charcuterie',
  POISSONNERIE: 'Poissonnerie',
  ROTISSERIE: 'Rôtisserie',
  BOULANGERIE: 'Boulangerie',
  PATISSERIE: 'Pâtisserie',
  FROMAGERIE: 'Fromagerie',
  TRAITEUR: 'Traiteur',
  PRODUITS_LAITIERS: 'Produits laitiers',
  OEUFS: 'Œufs',
  SURGELES: 'Surgelés',
  EPICERIE_SALEE: 'Épicerie salée',
  PATES_RIZ_CEREALES: 'Pâtes, riz & céréales',
  CONSERVES: 'Conserves',
  SAUCES_CONDIMENTS: 'Sauces & condiments',
  HUILES_VINAIGRES: 'Huiles & vinaigres',
  EPICES_AIDES_CULINAIRES: 'Épices & aides culinaires',
  PLATS_CUISINES: 'Plats cuisinés',
  SNACKING: 'Snacking (sandwichs & salades)',
  EPICERIE_SUCREE: 'Épicerie sucrée',
  BISCUITS_GATEAUX: 'Biscuits & gâteaux',
  CHOCOLATS_CONFISERIES: 'Chocolats & confiseries',
  PETIT_DEJEUNER: 'Petit-déjeuner (céréales & tartinables)',
  CAFE_THE: 'Café & thé',
  EAUX: 'Eaux',
  SODAS_JUS: 'Sodas & jus',
  BIERES: 'Bières',
  VINS_SPIRITUEUX: 'Vins & spiritueux',
  PRODUITS_BIO: 'Produits bio',
  SANS_GLUTEN_DIETETIQUE: 'Sans gluten & diététique',
  BEBE: 'Bébé (alimentaire & soins)',
  ANIMALERIE: 'Animalerie',
  ENTRETIEN_MAISON: 'Entretien de la maison',
  LESSIVE_SOIN_LINGE: 'Lessive & soin du linge',
  PAPIER_HYGIENE_MENAGERE: 'Papier & hygiène ménagère',
  HYGIENE_BEAUTE: 'Hygiène & beauté',
  PARAPHARMACIE: 'Parapharmacie',
  PAPETERIE_FOURNITURES: 'Papeterie & fournitures',
  PRESSE_LIVRES: 'Presse & livres',
  MAISON_DECO: 'Maison & déco',
  ARTS_DE_LA_TABLE: 'Arts de la table',
  TEXTILE: 'Textile',
  ELECTROMENAGER: 'Électroménager',
  MULTIMEDIA_HIGH_TECH: 'Multimédia & high-tech',
  BRICOLAGE: 'Bricolage',
  AUTO_MOBILITE: 'Auto & mobilité',
  JARDIN_PLANTES: 'Jardin & plantes',
  FLEURS: 'Fleurs',
  JEUX_JOUETS: 'Jeux & jouets',
  SAISONNIER: 'Saisonnier',
  NON_CLASSE: 'Non classé',
};

export function getAisleLabel(aisle: string | null | undefined): string {
  if (!aisle) return 'Non classé';
  return AISLE_LABELS[aisle] || aisle;
}
